version: '3.8'

services:
  journalscope:
    image: periodicos:5v
    container_name: journalscope-v5
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - VITE_APP_TITLE=JournalScope
      - VITE_APP_VERSION=5.0.0
    restart: unless-stopped
    volumes:
      - logs-nginx:/var/log/nginx

volumes:
  logs-nginx: