version: '3.8'

services:
  # JournalScope - Aplicação Principal Atualizada (usando Traefik global existente)
  journalscope-multidominio:
    image: periodicos:3v
    networks:
      - iaprojetos
    labels:
      - "traefik.enable=true"
      # Configuração para múltiplos domínios
      - "traefik.http.routers.journalscope-multi.rule=Host(`periodicos.iaprojetos.com.br`) || Host(`periodicos.iatranscreve.com.br`)"
      - "traefik.http.routers.journalscope-multi.entrypoints=websecure"
      - "traefik.http.routers.journalscope-multi.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.journalscope-multi.middlewares=security-headers"
      - "traefik.http.services.journalscope-multi.loadbalancer.server.port=80"
      # Certificados SSL para ambos os domínios
      - "traefik.http.routers.journalscope-multi.tls.domains[0].main=periodicos.iaprojetos.com.br"
      - "traefik.http.routers.journalscope-multi.tls.domains[1].main=periodicos.iatranscreve.com.br"
      # Headers de segurança aprimorados
      - "traefik.http.middlewares.security-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.security-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.security-headers.headers.referrerPolicy=strict-origin-when-cross-origin"
      - "traefik.http.middlewares.security-headers.headers.contentSecurityPolicy=default-src 'self' https:; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self' https:;"
      # Redirecionamento HTTP para HTTPS
      - "traefik.http.routers.journalscope-multi-http.rule=Host(`periodicos.iaprojetos.com.br`) || Host(`periodicos.iatranscreve.com.br`)"
      - "traefik.http.routers.journalscope-multi-http.entrypoints=web"
      - "traefik.http.routers.journalscope-multi-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    environment:
      - NODE_ENV=production
      - VITE_APP_TITLE=JournalScope
      - VITE_APP_VERSION=3.0.0
    volumes:
      - logs-nginx:/var/log/nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  iaprojetos:
    external: true

volumes:
  logs-nginx: